repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        verbose: false
        name: Commit message format
        stages:
          - commit-msg
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        name: Format files with prettier
        exclude: docker
        stages:
          - commit
        language_version: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        name: Kotlin format
        stages:
          - commit
        files: \.kt
        args: ["-w", "-o", "ktlintFormat"]
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        name: Kotlin static analysis
        stages:
          - commit
        files: \.kt
        args: ["-w", "-o", "ktlintCheck detektAll"]
fail_fast: true
