#!/usr/bin/env bash

export REPO_DIR="$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"

COLOR_GREEN="\x1b[32;01m"
COLOR_YELLOW="\x1b[33;01m"
COLOR_RED="\x1b[31;01m"
COLOR_RESET="\x1b[39;49;00m"

set -e

${REPO_DIR}/script/bootstrap


cd ${REPO_DIR}
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

if command -v sdk &> /dev/null
then
  echo -e $COLOR_GREEN"✅  java: sdk present - installing java sdk"$COLOR_RESET
  sdk env install
  echo -e $COLOR_GREEN"✅  java: installed $(java -version)"$COLOR_RESET
else
  echo -e $COLOR_GREEN"${COLOR_RED}❌  sdk not installed - please install: https://github.com/turo/developer-machine\n\t./tools/sdkman/install"$COLOR_RESET
  exit 1
fi

java -version
javac -version

echo -e $COLOR_GREEN"✅  App is now ready to go!"$COLOR_RESET
