# run when generating a new repo from this template.
name: Rename
# Controls when the workflow will run.
on:
  push:
    branches: [main]
jobs:
  renaming-job:
    name: Renaming Job
    if: ${{ github.repository != 'turo/coroutine-demo-msvc' }}
    runs-on: ["self-hosted", "general-ubuntu"]
    steps:
      - uses: actions/checkout@v2
      - name: renaming job
        env:
          GITHUB_TOKEN: ${{ secrets.ROLLSBOT_GITHUB_ACTIONS_TOKEN }}
          ORG_GRADLE_PROJECT_artifactoryAuthToken: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          ORG_GRADLE_PROJECT_artifactoryUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "renaming..."
          name=${{ github.event.repository.name }}
          ./rename-project.sh ${name/%-msvc/}
          mv .github/workflows/global/sync-environment.yaml .github/workflows/sync-environment.yaml
          rm .github/workflows/create.yaml
          rm ./rename-project.sh
          rm ./script/sync-environment
          rmdir .github/workflows/global
      - name: Create Pull Requestgit
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch-suffix: timestamp
          token: ${{ secrets.ROLLSBOT_GITHUB_ACTIONS_TOKEN }}
          base: main
          path: .
          commit-message: "chore: rename content of repo ${{ github.event.repository.name }}"
          title: "[bot] rename content of repository ${{ github.event.repository.name }}"
          body: |
            - Auto-generated by [create-pull-request][1]
              [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated
            auto-merge
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
